### PR TITLE
Map isless(a,b) to <(a,b)

### LINKED ISSUE #138: isless problem on .7 and windows
I get this error when trying to install gcc on .7.   

I suspect that in .6 maximum() used < to do comparisons and now it uses isless().  I think the correct fix is to add an override for isless(RPMVersionNumber, RPMVersionNumber).  But I wanted to open an issue to get feedback before doing so.  

```
julia> WinRPM.install("gcc", yes=true)
INFO: Multiple package candidates found for mingw64-unistd-pthread-devel, picking newest.
ERROR: MethodError: no method matching isless(::WinRPM.RPMVersionNumber, ::WinRPM.RPMVersionNumber)
Closest candidates are:
  isless(::Missing, ::Any) at missing.jl:56
  isless(::Any, ::Missing) at missing.jl:57
Stacktrace:
 [1] max(::WinRPM.RPMVersionNumber, ::WinRPM.RPMVersionNumber) at .\operators.jl:365
 [2] mapreduce_empty at .\reduce.jl:345 [inlined]
 [3] _mapreduce at .\reduce.jl:337 [inlined]
 [4] mapreduce at .\reduce.jl:358 [inlined]
 [5] maximum at .\reduce.jl:521 [inlined]
 [6] select(::WinRPM.Packages{Array{LibExpat.ETree,1}}, ::String) at C:\Users\matth\.julia\v0.7\WinRPM\src\WinRPM.jl:257
 [7] rpm_provides(::Set{AbstractString}) at C:\Users\matth\.julia\v0.7\WinRPM\src\WinRPM.jl:290
 [8] deps(::WinRPM.Package) at C:\Users\matth\.julia\v0.7\WinRPM\src\WinRPM.jl:353
 [9] prepare_install(::WinRPM.Package) at C:\Users\matth\.julia\v0.7\WinRPM\src\WinRPM.jl:399
 [10] #install#21(::Bool, ::Function, ::WinRPM.Package) at C:\Users\matth\.julia\v0.7\WinRPM\src\WinRPM.jl:372
 [11] #install at .\<missing>:0 [inlined]
 [12] #install#19 at C:\Users\matth\.julia\v0.7\WinRPM\src\WinRPM.jl:361 [inlined]
 [13] #install at .\<missing>:0 [inlined] (repeats 2 times)
 [14] top-level scope
```

### PR DESCRIPTION
**Pull request by RandomString123**
To fix #138 and ensure no breakage mapping an isless call to less than.

### CODE REVIEW

**Comment by nalimilan** [comment]
I think you should be able to drop all other comparison operators. Can you try that?

File: src/WinRPM.jl [hunk 1]
```diff
@@ -321,11 +321,7 @@ struct RPMVersionNumber
 end
 Base.convert(::Type{RPMVersionNumber}, s::AbstractString) = RPMVersionNumber(s)
 Base.:(<)(a::RPMVersionNumber, b::RPMVersionNumber) = false
-Base.:(==)(a::RPMVersionNumber, b::RPMVersionNumber) = true
```
Comment (nalimilan) [inline src/WinRPM.jl]: I don't think you can remove this definition. Have you tested it? OTC, is `<` really needed?

(I must say these constant definitions are really weird...)

Comment (RandomString123) [reply src/WinRPM.jl]: I did test it on all operations except for install because it is still failing due to a follow-on error.  I can put it back for now until I can test end-to-end without any issues.

< will be needed for backwards compatibility since maximum() calls < and not isless in .6

Comment (RandomString123) [reply src/WinRPM.jl]: I also agree they are really weird.  I think because there is a lot of repetition in the package list it is just trying to grab the first or last entry which represents the oldest or newest and really isn't doing any number based comparison.

Comment (tkelman) [reply src/WinRPM.jl]: this package is undertested, difficult to test, but heavily depended on, so please minimize the changes you make to it to be as low risk as possible. particularly if you are fixing 0.7-only issues, don't mix concerns and risk breaking 0.6.

Comment (RandomString123) [reply src/WinRPM.jl]: I agree with @tkelman  I rolled my changes back to just adding isless to get .7 to work.

**Comment by nalimilan** [comment]
@tkelman Merge if that's OK?
